import Head from "next/head";
import Image from "next/image";
import { useRef, useState, useEffect } from "react";
import Lottie from "lottie-react";
import { useLottie } from "lottie-react";
import bg_animation from "../animations/animated_melts.json";

import styled from "styled-components";
import useHorizontalScroller from "../hooks/useHorizontalScroller";
import Particles from "../components/Particles";
import BGCurves from "../components/BGCurves";

// let scrollbarWidth =
//   typeof window !== "undefined" &&
//   window.innerWidth - document.body.clientWidth;

const Container = styled.div`
  width: 100vw;
  height: 100vh;
  scrollbar-width: none;
  -ms-overflow-style: none;
  .overlay {
    width: 100vw;
    height: 100vh;
    /* background-color: black; */
    position: absolute;
    left: 0;
    top: 0;
    pointer-events: none;
    z-index: 1;
    backdrop-filter: brightness(70%) blur(25px) hue-rotate(-3deg) contrast(8) saturate(.88);
  }
  .pagesContent {
    scroll-snap-type: x mandatory;
    scroll-behavior: smooth;
    overflow-y: hidden;
    width: 100%;
    height: 100%;
    background-color: #eef;
    display: flex;
    .scrollPath {
      position: fixed;
      bottom: 0;
      left: 0;
      width: 100%;
      height: 2%;
      min-height: 15px;
      max-height: 50px;
      background-color: rgba(170, 170, 170, 0.6);
    }
    .progressBar {
      border-radius: 3px;
      position: fixed;
      bottom: 0;
      left: 0;
      width: 0%;
      height: 2%;
      min-height: 15px;
      max-height: 50px;
      background: linear-gradient(to right, #008aff, #00ffe7);
      pointer-events: none;
      transition: width 2s;
      animation: animate 5s linear infinite;
      &:before {
        content: "";
        position: absolute;
        bottom: 0;
        left: 100%;
        width: 0%;
        height: 100%;
        background: linear-gradient(to right, #008aff, #00ffe7);
        filter: blur(20px);
      }
      &:after {
        content: "";
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: linear-gradient(to right, #008aff, #00ffe7);
        filter: blur(40px);
      }
    }
    @keyframes animate {
      0%,
      100% {
        filter: hue-rotate(0deg);
      }
      50% {
        filter: hue-rotate(360deg);
      }
    }
    section {
      flex: none;
      scroll-snap-align: start;
      display: flex;
      justify-content: center;
      align-items: center;
      width: 100vw;
      height: 100vh;
      font-weight: bold;
      font-size: xxx-large;
      color: #323;
      background: none;
      h1 {
        /* font-family: 'Luckiest Guy', cursive; */
        font-family: "Amatic SC", cursive;
        font-weight: 700;
        /* font-family: 'Indie Flower', cursive; */
        /* font-family: 'IM Fell English SC', serif; */
        /* font-family: 'Gamja Flower', cursive; */
      }
    }
  }
`;

export default function Home() {
  const scrollerRef = useRef();
  const progressBarRef = useRef();
  const scrollPathRef = useRef();
  const bgRef = useRef();

  const horizontalScroller = useHorizontalScroller(
    scrollerRef,
    progressBarRef,
    scrollPathRef,
    bgRef
  );

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@400;700&family=Gamja+Flower&family=IM+Fell+English+SC&family=Indie+Flower&family=Luckiest+Guy&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Particles />
      <BGCurves ref={bgRef} />
      <div className="overlay" />

      <div
        className="pagesContent"
        ref={scrollerRef}
        style={{
          position: "relative",
        }}
      >
        <div
          className="progressBar"
          ref={progressBarRef}
          style={{ zIndex: 1001 }}
        />
        <div
          className="scrollPath"
          ref={scrollPathRef}
          style={{ zIndex: 1000 }}
        />

        <section style={{ zIndex: 1 }}>
          <h1>Page One</h1>
        </section>
        <section style={{ zIndex: 1 }}>
          <h1>Page Two</h1>
        </section>
        <section style={{ zIndex: 1 }}>
          <h1>Page Three</h1>
        </section>
        <section style={{ zIndex: 1 }}>
          <h1>Page Four</h1>
        </section>
        <section style={{ zIndex: 1 }}>
          <h1>Page Five</h1>
        </section>
      </div>
    </Container>
  );
}
